<a href="https://colab.research.google.com/github/imelike/Makine_Ogrenmesi_notlar/blob/main/KNN_HF6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv('diabetes.csv')

In [ ]:
X=df.drop('Outcome',axis=1)
y=df['Outcome']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
X_train.shape

(614, 8)

In [ ]:
import math
k=math.sqrt(len(X))
knn=KNeighborsClassifier(n_neighbors=27,metric='euclidean')
knn.fit(X_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=27)

In [ ]:
knn.score(X_test,y_test)

0.7532467532467533

In [ ]:
knn.score(X_train,y_train)

0.7671009771986971

In [ ]:
y_pred=knn.predict(X_test)
confusion_matrix(y_test,y_pred)

array([[88, 11],
       [27, 28]], dtype=int64)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.89      0.82        99
           1       0.72      0.51      0.60        55

    accuracy                           0.75       154
   macro avg       0.74      0.70      0.71       154
weighted avg       0.75      0.75      0.74       154



In [ ]:
for k in range(3,101,2):
    knn=KNeighborsClassifier(n_neighbors=k,metric='euclidean')
    knn.fit(X_train,y_train)
    print("k:",k," Score:",knn.score(X_test,y_test))

k: 3  Score: 0.7402597402597403
k: 5  Score: 0.7337662337662337
k: 7  Score: 0.7597402597402597
k: 9  Score: 0.7662337662337663
k: 11  Score: 0.7467532467532467
k: 13  Score: 0.7662337662337663
k: 15  Score: 0.7857142857142857
k: 17  Score: 0.7857142857142857
k: 19  Score: 0.7727272727272727
k: 21  Score: 0.7662337662337663
k: 23  Score: 0.7662337662337663
k: 25  Score: 0.7532467532467533
k: 27  Score: 0.7532467532467533
k: 29  Score: 0.7662337662337663
k: 31  Score: 0.7727272727272727
k: 33  Score: 0.7597402597402597
k: 35  Score: 0.7597402597402597
k: 37  Score: 0.7597402597402597
k: 39  Score: 0.7532467532467533
k: 41  Score: 0.7597402597402597
k: 43  Score: 0.7597402597402597
k: 45  Score: 0.7597402597402597
k: 47  Score: 0.7597402597402597
k: 49  Score: 0.7597402597402597
k: 51  Score: 0.7467532467532467
k: 53  Score: 0.7532467532467533
k: 55  Score: 0.7467532467532467
k: 57  Score: 0.7532467532467533
k: 59  Score: 0.7402597402597403
k: 61  Score: 0.7402597402597403
k: 63  Score: 

In [ ]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
      dtype=int64)

In [ ]:
df=pd.read_csv('iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
X=df.drop('species',axis=1)
y=df['species']
X.shape

(150, 4)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
for k in range(3,101,2):
    knn=KNeighborsClassifier(n_neighbors=k,metric='euclidean')
    knn.fit(X_train,y_train)
    print("k:",k," Score:",knn.score(X_test,y_test))

k: 3  Score: 1.0
k: 5  Score: 1.0
k: 7  Score: 0.9666666666666667
k: 9  Score: 0.9666666666666667
k: 11  Score: 0.9666666666666667
k: 13  Score: 0.9666666666666667
k: 15  Score: 0.9666666666666667
k: 17  Score: 0.9666666666666667
k: 19  Score: 0.9666666666666667
k: 21  Score: 0.9666666666666667
k: 23  Score: 0.9666666666666667
k: 25  Score: 0.9666666666666667
k: 27  Score: 0.9666666666666667
k: 29  Score: 0.9666666666666667
k: 31  Score: 0.9666666666666667
k: 33  Score: 0.9666666666666667
k: 35  Score: 0.9666666666666667
k: 37  Score: 0.9666666666666667
k: 39  Score: 0.9666666666666667
k: 41  Score: 0.9666666666666667
k: 43  Score: 0.9666666666666667
k: 45  Score: 0.9666666666666667
k: 47  Score: 0.9666666666666667
k: 49  Score: 0.9333333333333333
k: 51  Score: 0.9333333333333333
k: 53  Score: 0.9333333333333333
k: 55  Score: 0.9
k: 57  Score: 0.9
k: 59  Score: 0.9
k: 61  Score: 0.9
k: 63  Score: 0.9
k: 65  Score: 0.9
k: 67  Score: 0.9
k: 69  Score: 0.8
k: 71  Score: 0.8333333333333334

In [ ]:
knn=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score,cross_val_predict
cv=KFold(n_splits=3,random_state=1,shuffle=True)

knn=KNeighborsClassifier(n_neighbors=3,metric='euclidean')

scores=cross_val_score(knn,X,y,scoring='recall',cv=cv)

print(np.mean(scores))

0.5315586797869364


In [ ]:
print(scores)

[0.52173913 0.57831325 0.49462366]


In [ ]:
pred=cross_val_predict(knn,X,y,cv=cv)

In [ ]:
pred

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
from sklearn.linear_model import LogisticRegression

log=LogisticRegression(max_iter=200)
log.fit(X_train,y_train)
y_pred=log.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84        99
           1       0.76      0.56      0.65        55

    accuracy                           0.78       154
   macro avg       0.77      0.73      0.74       154
weighted avg       0.78      0.78      0.77       154



In [ ]:
from sklearn.model_selection import GridSearchCV

log=LogisticRegression(max_iter=200)

pram_grid={
    'C':[0.001,0.01,0.1,1,10,100],
    'penalty':['l1','l2'],

}
grid_search=GridSearchCV(log,pram_grid,cv=5,scoring='accuracy')
results=grid_search.fit(X_train,y_train)
print(results.best_params_)

C:\Users\mf\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\mf\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\mf\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1304, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\mf\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 442, in _check_solver
    raise ValueError("Solver %s supports only 'l2' or 'none' penalties, "
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\mf\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:54

{'C': 0.01, 'penalty': 'l2'}


In [ ]:
from sklearn.linear_model import LogisticRegression

log=LogisticRegression(max_iter=300,C=0.01,penalty='l2')
log.fit(X_train,y_train)
y_pred=log.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.90      0.84        99
           1       0.75      0.55      0.63        55

    accuracy                           0.77       154
   macro avg       0.77      0.72      0.73       154
weighted avg       0.77      0.77      0.76       154



In [ ]:
knn=KNeighborsClassifier()
param_grid={
    'n_neighbors':np.arange(1,50),
    'weights':['uniform', 'distance'],
    'metric':['euclidean','cosine','infinity'],
}
grid_search=GridSearchCV(knn,param_grid,cv=5)
result=grid_search.fit(X_train,y_train)
print(result.best_params_)

{'metric': 'euclidean', 'n_neighbors': 30, 'weights': 'distance'}


In [ ]:
math.sqrt(len(X))

27.712812921102035

In [ ]:
knn=KNeighborsClassifier(n_neighbors=29,metric='euclidean',weights='distance')
knn.fit(X_train,y_train)
pred=knn.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.78      0.90      0.84        99
           1       0.75      0.55      0.63        55

    accuracy                           0.77       154
   macro avg       0.77      0.72      0.73       154
weighted avg       0.77      0.77      0.76       154

