<a href="https://colab.research.google.com/github/imelike/Makine_Ogrenmesi_notlar/blob/main/YL_Logistic_Regresion_HF_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('weight-height.csv')
df.head(5)

Gender       Kilo         Boy
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [ ]:
df.shape

(10000, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Kilo    10000 non-null  float64
 2   Boy     10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


In [ ]:
df.isnull().values.any()

False

In [ ]:
df[df['Gender']=='Male'].shape

(0, 3)

In [ ]:
df.groupby('Gender').mean()

Kilo         Boy
Gender                       
0       69.026346  187.020621
1       63.708774  135.860093

In [ ]:
df['Gender'].replace('Male',0,inplace=True)
df['Gender'].replace('Female',1,inplace=True)

In [ ]:
df.head()

Gender       Kilo         Boy
0       0  73.847017  241.893563
1       0  68.781904  162.310473
2       0  74.110105  212.740856
3       0  71.730978  220.042470
4       0  69.881796  206.349801

In [ ]:
X=df[['Kilo','Boy']]
y=df['Gender']

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=58)


In [ ]:
from sklearn.linear_model import LogisticRegression

lg=LogisticRegression()
model=lg.fit(X_train,y_train)

In [ ]:
model.coef_

array([[ 0.503965  , -0.19899705]])

In [ ]:
model.intercept_

array([-1.3125409])

In [ ]:
model.score(X_test,y_test)

0.9305

In [ ]:
model.score(X_train,y_train)

0.915875

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,classification_report

pred=model.predict(X_test)

confusion_matrix(y_test,pred)

array([[944,  73],
       [ 66, 917]], dtype=int64)

In [ ]:
recall_score(y_test,pred)

0.9328585961342828

In [ ]:
917/(917+66)

0.9328585961342828

In [ ]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93      1017
           1       0.93      0.93      0.93       983

    accuracy                           0.93      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.93      0.93      0.93      2000



In [ ]:
pred

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [ ]:
model.predict([[85,165]])

array([1], dtype=int64)